steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build server binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -ldflags="-s -w" -o aetherlink-server-${{ matrix.suffix }} ./cmd/lt-server

    - name: Build client binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -ldflags="-s -w" -o aetherlink-client-${{ matrix.suffix }} ./cmd/lt-client

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.suffix }}
        path: |
          aetherlink-server-${{ matrix.suffix }}
          aetherlink-client-${{ matrix.suffix }}
